export const categoryGroupCode: CategoryGroupCode = {
  mart: "MT1",
  convenient_store: "CS2",
  preschool: "PS3",
  school: "SC4",
  academy: "AC5",
  parking: "PK6",
  oil: "OL7",
  subway: "SW8",
  bank: "BK9",
  culture: "CT1",
  agency: "AG2",
  public_organizations: "PO3",
  attraction_tour: "AT4",
  accommodation: "AD5",
  food: "FD6",
  cafe: "CE7",
  hospital: "HP8",
  pharmacy: "PM9",
};
